name: Run Build and Push
on:
  workflow_dispatch:
    inputs:
        Name:
            description: Main Branch
            required: true
            default: 'Main Branch'
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm run inst
    - run: npm ci
    - run: npm run build
    - name: Commit changes
      id: "add-and-commit"
      uses: EndBug/add-and-commit@v9
      with:
        add: "space-lively-wallpaper.zip"
        message: "Update"
        author_name: "ProjectSoft-STUDIONIONS"
        author_email: "projectsoft2009@yandex.ru"
        committer_name: "ProjectSoft-STUDIONIONS"
        committer_email: "projectsoft2009@yandex.ru"
